name: Build on PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm ci
#      - run: npm run lint
      - run: npm test
      - run: npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: Content Platforms::recipes-backend
          configPath: "cdk/cdk.out/riff-raff.yaml"
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out/RecipesBackend-euwest-1-CODE.template.json
              - cdk/cdk.out/RecipesBackend-euwest-1-PROD.template.json
            recipes-backend-testindex:
              - dist/lambda/test-indexbuild-lambda.zip
